### ISSUE TITLE
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#103]
Getting this warning when running the tests:

```
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
```

Need to update.

**Comment by nelsonic** [comment]
Appears to be in _Phoenix_ ...

```
warning: :simple_one_for_one strategy is deprecated, please use DynamicSupervisor instead
  (elixir 1.10.3) lib/supervisor.ex:604: Supervisor.init/2
  (elixir 1.10.3) lib/supervisor.ex:556: Supervisor.start_link/2
  (phoenix 1.4.4) lib/phoenix/socket/pool_supervisor.ex:31: Phoenix.Socket.PoolSupervisor.start_pooled/3
  (stdlib 3.13) supervisor.erl:385: :supervisor.do_start_child_i/3
  (stdlib 3.13) supervisor.erl:371: :supervisor.do_start_child/2
  (stdlib 3.13) supervisor.erl:355: anonymous fn/3 in :supervisor.start_children/2
```

See: https://github.com/elixir-lang/elixir/issues/9416#issuecomment-542552344

So basically, just update Phoenix!

**Comment by nelsonic** [comment]
https://gist.github.com/chrismccord/e53e79ef8b34adf5d8122a47db44d22f

**Comment by nelsonic** [comment]
Fixed in PR https://github.com/dwyl/hits/pull/82
