### ISSUE TITLE
Chore: no route found for GET /favicon.ico

### ISSUE THREAD

**Issue by nelsonic** [dwyl/hits#296]
```sh
mix s
```
Visit: http://localhost:4000/
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/10965be7-1ffc-47a5-887b-6e1899192b8a">

Terminal:
```sh
[info] GET /favicon.ico
[debug] ** (Phoenix.Router.NoRouteError) no route found for GET /favicon.ico (HitsWeb.Router)
    (hits 1.7.1) deps/phoenix/lib/phoenix/router.ex:541: HitsWeb.Router.call/2
    (hits 1.7.1) lib/hits_web/endpoint.ex:1: HitsWeb.Endpoint.plug_builder_call/2
    (hits 1.7.1) deps/plug/lib/plug/debugger.ex:136: HitsWeb.Endpoint."call (overridable 3)"/2
    (hits 1.7.1) lib/hits_web/endpoint.ex:1: HitsWeb.Endpoint.call/2
    (phoenix 1.7.14) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (plug_cowboy 2.7.2) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
    (cowboy 2.12.0) /hits/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
    (cowboy 2.12.0) /hits/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
    (cowboy 2.12.0) /hits/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
    (stdlib 5.2.3) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
```

**Comment by nelsonic** [comment]
Borrowing: 
https://github.com/dwyl/mvp/blob/71b44f869dc2f1c83be5d1c257019a90276075d6/lib/app_web/templates/layout/icons.html.heex
